-- Generated from db/chronoatlas.sqlite. Do not edit by hand.
-- Rebuild with: npm run db:seed:export
-- Split seed manifest for core-data.
-- part: core-data.part-001.sql
-- part: core-data.part-002.sql
-- part: core-data.part-003.sql
