-- Generated from db/chronoatlas.sqlite. Do not edit by hand.
-- Rebuild with: npm run db:seed:export
-- Split seed manifest for runtime-data.
-- part: runtime-data.part-001.sql
-- part: runtime-data.part-002.sql
